apiVersion: v1
kind: ConfigMap
metadata:
  name: "user-configuration-1"
  labels:
    type: "Jenkins-Jenkins-config"
data:
  1-system-message.yaml: |
    security:
      gitHostKeyVerificationConfiguration:
        sshHostKeyVerificationStrategy: "noHostKeyVerificationStrategy"
    jenkins:
      systemMessage: "New message New version of Configuration as Code integration works!!!"
      numExecutors: 5
      scmCheckoutRetryCount: 2
      mode: NORMAL
