apiVersion: v1
kind: Secret
metadata:
# this is the jenkins id.
  name: "github-secret"
  labels:
    "jenkins.io/credentials-type": "secretText"
  annotations:
# description - can not be a label as spaces are not allowed
    "jenkins.io/credentials-description" : "secret text credential for github api"
type: Opaque
stringData:
  text: MySecret
