apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: application
  name: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  strategy: {}
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - image: localhost:5000/app
        #- image: host.docker.internal:5000/app
        #- image: gcr.io/google-containers/echoserver:1.10
        name: application
        ports:
          - containerPort: 80
