apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: default
spec:
  dnsNames:
    - example.com
  secretName: selfsigned-cert-tls-long
  issuerRef:
    name: test-selfsigned
  duration: 24000h # 1000 days
  renewBefore: 23000h 
